made changes related to the issue discussion
united-manufacturing-hub/umh.docs.umh.app pull request #153
Opened 2023-09-13 20:05 UTC by ricardo-maestas

# Description

Addresses the issues I discovered while setting up my own local environment to make documentation contributions.

## Related issues

Fixes #152 

## Checklist

*You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [contributing guidelines](https://umh.docs.umh.app/docs/development/contribute/new-content/add-documentation/) and the [code of conduct](CODE_OF_CONDUCT.md).
- [ ] I have followed the [documentation](https://umh.docs.umh.app/docs/development/contribute/documentation/style/) style.

## Additional information

2023-09-14 08:30 UTC, DaruZero requested changes
Thanks for your contribution! Other than that small copy paste typo, it looks great 😃

2023-09-14 12:45 UTC, ricardo-maestas commented on umh.docs.umh.app/content/en/docs/development/contribute/new-content/add-documentation.md
> +   origin  https://github.com/ricardo-maestas/umh.docs.umh.app.git (push)
😆 yes of course.

2023-09-14 13:42 UTC, DaruZero approved these changes
Fantastic! 🚀

2023-09-15 06:37 UTC, Scarjit approved these changes

2023-09-20 14:19 UTC, merged