updating installation page
united-manufacturing-hub/umh.docs.umh.app pull request #163
Opened 2023-11-20 16:13 UTC by Ayato77

# Description

Updating [installation](https://umh.docs.umh.app/docs/getstarted/installation/) page in the get started tutorial of umh documentation

## Related issues

united-manufacturing-hub/MgmtIssues#1039

## Checklist

*You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [contributing guidelines](https://umh.docs.umh.app/docs/development/contribute/new-content/add-documentation/) and the [code of conduct](CODE_OF_CONDUCT.md).
- [x] I have followed the [documentation](https://umh.docs.umh.app/docs/development/contribute/documentation/style/) style.

## Additional information

2023-11-20 16:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/united-manufacturing-hub/umh.docs.umh.app?pullRequest=163) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/united-manufacturing-hub/umh.docs.umh.app?pullRequest=163) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/united-manufacturing-hub/umh.docs.umh.app?pullRequest=163) it.</sub>

2023-11-20 17:20 UTC, Ayato77 commented on umh.docs.umh.app/content/en/docs/getstarted/installation.md
> +  **The Management Console provides a demo mode for a quick overview without additional setups.**
commented in the issue page

2023-11-21 08:28 UTC, JeremyTheocharis requested changes
I did a lot of changes/notes directly in the code (see also comments).

2023-11-21 12:14 UTC, Ayato77 commented
URL of the flatcar installation page must be updated after united-manufacturing-hub/MgmtIssues#1049 is completed.

2023-11-21 14:41 UTC, JeremyTheocharis requested changes

2023-11-21 16:59 UTC, JeremyTheocharis approved these changes

2023-11-21 16:59 UTC, merged