Ensure that "Data Infrastructure / Alerting" page is up to standard
united-manufacturing-hub/umh.docs.umh.app pull request #179
Opened 2023-11-28 17:44 UTC by Ayato77

# Description

Adjust page to the new page structure and mgmt console

## Related issues

closes united-manufacturing-hub/MgmtIssues/issues/1060

## Checklist

*You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [contributing guidelines](https://umh.docs.umh.app/docs/development/contribute/new-content/add-documentation/) and the [code of conduct](CODE_OF_CONDUCT.md).
- [x] I have followed the [documentation](https://umh.docs.umh.app/docs/development/contribute/documentation/style/) style.

2023-11-29 08:02 UTC, JeremyTheocharis requested changes

2023-11-29 08:02 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/features/datainfrastructure/postgresql_and_grafana_alerts.md
>  ## How can I use it?
Can we integrate the learn article in here, and use our new data source in the new data model for it?

2023-12-11 14:25 UTC, Ayato77 commented on umh.docs.umh.app/content/en/docs/features/datainfrastructure/postgresql_and_grafana_alerts.md
> +### Install the PostgreSQL plugin in Grafana
Ok, I removed this part:)

Also, I installed a new UMH, created a connection with the get started guide for the test. My discord server recieved the alert successfully.

2023-12-11 18:22 UTC, JeremyTheocharis approved these changes

2023-12-11 20:01 UTC, merged