Remove Lens from production guides
united-manufacturing-hub/umh.docs.umh.app pull request #192
Opened 2023-12-19 15:54 UTC by DaruZero

# Description

This PR aims to remove as much references to Lens as possible. The main job is to just translate whatever action was performed in Lens into a normal shell command, not to adjust the guides themselves (see also additional info below).

I did not remove Lens from past upgrade guides, pages marked as draft (k3d installation) and pages that will be deprecated (see also additional info below).

## Related issues

Close https://github.com/united-manufacturing-hub/MgmtIssues/issues/1322

## Checklist

*You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [contributing guidelines](https://umh.docs.umh.app/docs/development/contribute/new-content/add-documentation/) and the [code of conduct](CODE_OF_CONDUCT.md).
- [x] I have followed the [documentation](https://umh.docs.umh.app/docs/development/contribute/documentation/style/) style.

## Additional information

There are many guides that may need a complete revision or even a definitive deprecation. Here's a non-comprehensive list that I wrote while working on this PR:

**To revise**:
- `administration/access-services-from-outside-cluster.md`
- `administration/delete-assets.md`
- `administration/optimize-database-datatypes.md`
- `administration/optimize-time-consuming-queries.md`
- `administration/reduce-database-size.md`

**To deprecate**:
- `administration/access-kafka-outside-cluster.md`
- `security/change-vernemq-acl-configuration.md`

In general though, I would give a deeper look into all the guides, and test if they still work with the latest changes. 

Also, in the [historian ](https://umh.docs.umh.app/docs/datamodel/database/#data-retrieval) page of the new data model there are instruction on how to access the database. Personally, I would suggest to just update the guide on how to access the database and reference it from the data model page

2023-12-21 10:43 UTC, JeremyTheocharis requested changes

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/administration/access-database.md
>  ```bash
This is used I think in different places now. Previously I added an test that checks if this works. Can you modify the test as well that checks if this works? Additionally, can you ensure through comments etc. that any changes here must pass the automated test?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/administration/access-database.md
>  ```bash
`<!-- This command is tested within #1153 -->`

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/administration/access-services-from-outside-cluster.md
> +1. Access your instance via SSh
SSH

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/administration/access-services-from-outside-cluster.md
> +   ```bash
Can we add a test that will test whether this command will work? similar to the ones to get credentials?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/administration/execute-kafka-shell-scripts.md
>     ```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/administration/explore-cached-data.md
> +   ```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/administration/expose-grafana-to-internet.md
> +```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/administration/install-custom-drivers-nodered.md
> +```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/administration/install-custom-drivers-nodered.md
> +      ```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/administration/install-custom-drivers-nodered.md
> +```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/administration/optimize-time-consuming-queries.md
> +```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/backup_recovery/backup-restore-database.md
> +```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/backup_recovery/backup-restore-database.md
> +```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/backup_recovery/backup-restore-umh.md
> +```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/security/enable-rbac-mqtt-broker.md
> +```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/security/enable-rbac-mqtt-broker.md
> +1. Open a shell inside the Pod:
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/security/enable-rbac-mqtt-broker.md
> +    ```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/security/enable-rbac-mqtt-broker.md
> +
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/security/setup-pki-mqtt-broker.md
> +```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-21 10:43 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/includes/open-database-shell.md
> +```bash
Can we add a test checking that this command will work in the E2E tests?

2023-12-22 09:01 UTC, DaruZero commented
Added tests for most of the commands in [this PR](https://github.com/united-manufacturing-hub/ManagementConsole/pull/258). `helm upgrade` commands are quite tricky to test, thus I left them out of the PR. Same goes for accessing the `psql` shell in the TimescaleDB pod. Everything else is tested

2023-12-22 13:07 UTC, JeremyTheocharis approved these changes

2023-12-22 13:36 UTC, merged