upgrade instructions and changelog
united-manufacturing-hub/umh.docs.umh.app pull request #263
Opened 2024-03-11 14:07 UTC by Scarjit

This pr adds the changelog for UMH 0.13.3 (0.2.15)

2024-03-12 10:26 UTC, JeremyTheocharis requested changes

2024-03-12 10:26 UTC, JeremyTheocharis commented on umh.docs.umh.app/content/en/docs/production-guide/upgrading/0.13.3.md
> +sudo $(which helm) upgrade united-manufacturing-hub united-manufacturing-hub/united-manufacturing-hub -n united-manufacturing-hub --version 0.13.4 --reuse-values --kubeconfig /etc/rancher/k3s/k3s.yam
no schema migrations?

2024-03-12 14:04 UTC, Scarjit commented
@JeremyTheocharis The migration is quite long.
We could put it into a bash script and do a `bash <(curl -s https://umh.docs.umh.app/path/to/script.sh)`

2024-03-12 14:11 UTC, Scarjit commented
It would also allow a bit cleaner handling of already existing stuff like users and databases

2024-03-12 14:14 UTC, JeremyTheocharis commented
What about https://management.umh.app/upgrading/upgrading-to-0.95.3.sh ?

2024-03-12 15:45 UTC, Scarjit commented
![image](https://github.com/united-manufacturing-hub/umh.docs.umh.app/assets/6317420/89004cac-03ab-45be-a15a-c99e58d86f98)

Im now creating the redirect

2024-03-13 07:51 UTC, JeremyTheocharis approved these changes

2024-03-13 07:53 UTC, JeremyTheocharis requested changes
would this not make more sense in the managementconsole repo?

2024-03-13 13:37 UTC, merged