Added features section
united-manufacturing-hub/umh.docs.umh.app pull request #60
Opened 2023-03-08 15:55 UTC by JeremyTheocharis

Still as a draft until the analytics feature is finished. Feedback would be great.

Added @Scarjit and @DaruZero as reviewers, as these articles provide a different perspective on our documentation and show where there is stuff missing (e.g., where do we have the historian functionalitiies like min, max, downsampling, etc. documented).

2023-03-13 08:54 UTC, DaruZero commented
Maybe consider writing a "features" archetype? so that in the future if we want to add more pages we have a skel for it

2023-03-14 10:13 UTC, Scarjit requested changes

2023-03-14 10:13 UTC, Scarjit commented on umh.docs.umh.app/content/en/docs/features/unified-namespace/index.md
> +## What are the limitations?
Max 249 chars (https://github.com/apache/kafka/commit/ad3dfc6ab25c3f80d2425e24e72ae732b850dc60)
Legal char regex: [a-zA-Z0-9\\._\\-]

2023-03-14 10:13 UTC, Scarjit commented on umh.docs.umh.app/content/en/docs/features/unified-namespace/index.md
> +## What are the limitations?
Max message size defaults to 1000000 byte (https://docs.confluent.io/4.0.0/clients/librdkafka/CONFIGURATION_8md.html)

2023-03-14 10:13 UTC, Scarjit commented on umh.docs.umh.app/content/en/docs/features/unified-namespace/index.md
> +- Efficiently process messages from millions of devices: The Unified Namespace is designed to handle messages from millions of devices in your factory, even over unreliable connections. By using Kafk
"at-least-once" -> 1 or more times, not "no data is lost or duplicated."

2023-03-14 15:53 UTC, Scarjit approved these changes

2023-03-14 15:58 UTC, merged