added namespace
united-manufacturing-hub/umh.docs.umh.app pull request #85
Opened 2023-03-14 14:51 UTC by krgrsebastian

# Description
added description to change namespace in lens

### Related issues

#76 

## Type of change

What types of changes does your code introduce to this project?

- [ x] Bug fix (non-breaking change which fixes an issue)

2023-03-14 15:16 UTC, DaruZero requested changes
Button names should be capitalized. e.g. **Workloads** -> **Pods**

2023-03-14 15:16 UTC, DaruZero commented on umh.docs.umh.app/content/en/docs/getstarted/managingthesystem.md
> +4. To access the web interfaces of the microservices, e.g. node-red or grafana, navigate to **network**->**services** on the left-hand side. Again make sure to change the namespace to **Namespace: un
use `resource` shortcode for namespace name

2023-03-22 11:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/united-manufacturing-hub/umh.docs.umh.app?pullRequest=85) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/united-manufacturing-hub/umh.docs.umh.app?pullRequest=85) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/united-manufacturing-hub/umh.docs.umh.app?pullRequest=85) it.</sub>

2023-03-22 11:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/united-manufacturing-hub/umh.docs.umh.app?pullRequest=85) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/united-manufacturing-hub/umh.docs.umh.app?pullRequest=85) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/united-manufacturing-hub/umh.docs.umh.app?pullRequest=85) it.</sub>

2023-04-06 08:35 UTC, Scarjit commented
@JeremyTheocharis Can you check the CLA error here ?

2023-04-28 09:05 UTC, DaruZero requested changes
Can you consider opening a new issue regarding the styling of the whole getstarted section?

2023-04-28 09:05 UTC, DaruZero commented on umh.docs.umh.app/content/en/docs/getstarted/managingthesystem.md
> +3. You can check the status of all pods by navigating to **workloads** -> **pods** and selecting
Capitalize button names

2023-04-28 09:05 UTC, DaruZero commented on umh.docs.umh.app/content/en/docs/getstarted/managingthesystem.md
> +4. To access the web interfaces of the microservices, e.g. node-red or grafana, navigate to **network**->**services** on
Capitalize button names

2023-05-02 10:22 UTC, JeremyTheocharis approved these changes

2023-05-05 11:34 UTC, merged